name: Frontend CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  frontend-build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install ESLint
        run: pnpm add -D eslint

      - name: Lint (ESLint)
        run: pnpm exec eslint . --ext .js,.jsx,.ts,.tsx || true

      - name: Run Unit & Integration Tests (Vitest)
        run: pnpm vitest run

  docker-build:
    runs-on: ubuntu-latest
    needs: frontend-build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t nextjs-frontend-test .

      - name: Run Docker container (healthcheck)
        run: |
          docker run -d -p 3000:3000 --name nextjs-frontend-test nextjs-frontend-test
          sleep 10
          curl -f http://localhost:3000 || (docker logs nextjs-frontend-test && exit 1)
          docker stop nextjs-frontend-test
          docker rm nextjs-frontend-test
